### ISSUE TITLE
Error Uploading Cookbook to Chef Supermarket.

### ISSUE THREAD

**Issue by srirammageswaran** [cwebberOps/knife-supermarket#34]
When i try to upload cookbook i get an exception

ERROR: Tarball has contents that are not what they are reported to be

knife supermarket share cookbook_name -VV -o . --supermarket-site https://XXXXXXXX.YYYYY.com

Knife Supermarket gem version in 0.3.0.

Thanks ,
Sriram Mageswaran

**Comment by thommay** [comment]
`knife supermarket` is unsupported, and we recommend that you uninstall it and use the built in version in chef, or a third party tool such as stove, which are both included in the Chef DK.
This project is deprecated, which means that we don't devote engineering time to fixing issues or tracking them down, simply recommending that our users move to tools that will give them a better experience.
I'll be closing this ticket.

**Comment by srirammageswaran** [comment]
@thommay  Thanks . Will raise a diff issue in chef dk. I Still face the same in latest version in chefdk.
