### ISSUE TITLE
Merge with knife toolkit (replace knife cookbook site)

### ISSUE THREAD

**Issue by echohack** [cwebberOps/knife-supermarket#6]
Since the oldschool Opscode community site is now dead, this knife plugin's functionality should be the default in the knife toolset. Please move this code appropriately.

**Comment by leftathome** [comment]
:+1:
I'm writing up a document telling internal users how to upload cookbooks to internal Supermarket and `knife cookbook site` is kind of a land mine for us...

**Comment by cmluciano** [comment]
@lamont-granquist @echohack Should all cookbook_site_* be moved to here or just the specific functionality for sharing cookbooks?

**Comment by lamont-granquist** [comment]
I'm not sure, I tend to use berkshelf for downloading cookbooks and stove for uploading to the community site, so I'm no longer very familiar with all the different commands here.

**Comment by echohack** [comment]
It's been a while since I've tested on this, but the documentation has updated to push to supermarket...?

https://docs.chef.io/knife_cookbook_site.html

Unsure if this means that the knife tool has changed or what... will need to test again....

**Comment by cmluciano** [comment]
I still see old opscode links here https://github.com/chef/chef/blob/master/lib/chef/knife/cookbook_site_share.rb#L111

**Comment by cwebberOps** [comment]
So really, reading through this issue, it should actually be opened on the chef/chef repo. In an ideal world, we update the cookbook site functionality or remove it in favor of a supermarket sub command. I am going to go ahead and close this issue since it is out of scope of this repo.

Thank you for the discussion.
